version: "3.9"
services:

  postgresql:
    image: postgres:15.1-alpine
    env_file:
      - .env
    volumes:
      - ./postgres-data:/var/lib/postgresql/data

  redis:
    image: redis:7.0.7-alpine
    restart: always

  web:
    build: ./app
    restart: on-failure
    env_file:
      - .env
    volumes:
      - media_volume:/usr/src/app/media"
    depends_on:
      - postgresql
      - redis

  nginx:
    build: ./nginx
    ports:
      - "80:80"
    volumes:
      - media_volume:/usr/src/app/media"
    depends_on:
      - web

volumes:
  media_volume: