version: "3.9"
services:

  postgresql:
    image: postgres:15.1-alpine
    env_file:
      - .env
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  redis:
    image: redis:7.0.7-alpine
    restart: always
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  web:
    build: ./app
    restart: on-failure
    env_file:
      - .env
    volumes:
      - media_volume:/usr/src/app/media
    depends_on:
      - postgresql
      - redis
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  nginx:
    build: ./nginx
    ports:
      - "80:80"
    volumes:
      - media_volume:/usr/src/app/media
    depends_on:
      - web
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

volumes:
  media_volume: