version: "3.9"
services:

  postgresql:
    image: postgres:15.1-alpine
    env_file:
      - .env
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  redis:
    image: redis:7.0.7-alpine
    restart: always
    ports:
      - "6379:6379"

  web:
    build: ./app
    restart: on-failure
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - ./app:/usr/src/app
      - ./app/media:/usr/src/app/media
    depends_on:
      - postgresql
      - redis

  nginx:
    build: ./nginx
    ports:
      - "80:80"
    volumes:
      - ./app/media:/usr/src/app/media
    depends_on:
      - web

  alertmanager:
    image: prom/alertmanager
    volumes:
      - ./etc/alertmanager/alertmanager.conf:/etc/alertmanager/alertmanager.conf
    command:
      - "--config.file=/etc/alertmanager/alertmanager.conf"
    ports:
      - "9093:9093"

  prometheus:
    image: prom/prometheus
    volumes:
      - ./etc/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - ./etc/prometheus/alert_rules.yml:/etc/prometheus/alert_rules.yml
      - prometheus_data:/prometheus
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
    links:
      - alertmanager
    ports:
      - "9090:9090"

  grafana:
    image: grafana/grafana
    volumes:
      - ./etc/grafana/datasources/datasources.yml:/etc/grafana/provisioning/datasources/all.yaml
      - ./etc/grafana/config/config.ini:/etc/grafana/config.ini
      - grafana_data:/var/lib/grafana
    ports:
      - "3000:3000"

volumes:
  prometheus_data: {}
  grafana_data: {}
