app:
  dirs:
    base: "/usr/src/app"
  server:
    http:
      host: "0.0.0.0"
      port: "8000"
  token:
    ttl: 720h

postgresql:
  host: "postgresql"
  port: "5432"

redis:
  host: "redis"
  port: "6379"