app:
  dirs:
    base: "/usr/src/app"
    media: "/media/"
  server:
    http:
      host: "0.0.0.0"
      port: "8000"
  token:
    ttl: 2160h
  stats:
    ttl: 72h

postgresql:
  host: "postgresql"
  port: "5432"

redis:
  host: "redis"
  port: "6379"